# Generated by Django 3.1.3 on 2020-11-27 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedSummary',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('link', models.URLField()),
                ('description', models.TextField()),
                ('published', models.DateTimeField()),
                ('source', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FeedDetail',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('post', models.TextField(blank=True, null=True)),
                ('feed_summary', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='feeds.feedsummary')),
            ],
        ),
    ]
