# Generated by Django 3.2 on 2021-05-01 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_squashed_0005_auto_20210104_0704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedsource',
            name='last_refreshed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
