# Generated by Django 3.1.3 on 2021-01-02 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_auto_20210102_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedsummary',
            name='title_detail',
        ),
    ]
