# Generated by Django 3.2 on 2021-05-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_auto_20210501_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedsource',
            name='url_slug',
            field=models.SlugField(default='null', max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
