# Generated by Django 3.1.3 on 2021-01-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0004_feedsources'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedEntry',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('author', models.CharField(max_length=500)),
                ('link', models.URLField()),
                ('summary', models.TextField()),
                ('published', models.DateTimeField()),
                ('updated', models.DateTimeField()),
                ('source', models.CharField(max_length=200)),
                ('article', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='FeedSources',
            new_name='FeedSource',
        ),
        migrations.DeleteModel(
            name='FeedDetail',
        ),
        migrations.DeleteModel(
            name='FeedSummary',
        ),
    ]
