from django.http import HttpResponse
from django.db.utils import IntegrityError
from django.shortcuts import render
from feeds.reader import FeedReader
from feeds.models import FeedSource, FeedEntry


def load_objects(request):
    """ Load objects from source to DB """
    # Handle duplicates
    f = FeedSource.objects.all()
    source_posts = list(map(lambda x: FeedReader(x.feed_url).posts(), f))
    for source in source_posts:
        for item in source:
            try:
                FeedEntry.objects.create(**item)
            except IntegrityError:
                # Ignore errors for now
                pass
    return HttpResponse('Loaded objects')

# TODO: Replace this section with autogenerated urls.


def get_feeds_context(source, name, reader_class=FeedReader):
    feed = FeedEntry.objects.filter(source=source)
    context = {
        'posts': feed,
        'title': name
    }
    return context


def root(request):
    context = {
        'urls': [
            {
                'name': 'Sky Sports',
                'link': '/skysports/',
            },
            {
                'name': 'MoneyControl - Top News',
                'link': '/moneycontrol/',
            },
            {
                'name': 'Girl With the Jacket',
                'link': '/gwtj/',
            },
            {
                'name': 'Scroll.in',
                'link': '/scroll.in/',
            },
            {
                'name': 'The News Minute',
                'link': '/thenewsminute/',
            },
        ],
        'title': 'Feed List',
    }
    return render(request, 'feed_list.html', context=context)


def sky_sports_reader_view(request):
    context = get_feeds_context('www.skysports.com', 'Sky Sports')
    return render(request, 'feed_reader.html', context)


def gwtj_reader_view(request):
    context = get_feeds_context('girlwiththejacket.wordpress.com', 'MoneyControl - Top News')
    return render(request, 'feed_reader.html', context)


def moneycontrol_reader_view(request):
    context = get_feeds_context('www.moneycontrol.com', 'Girl With the Jacket')
    return render(request, 'feed_reader.html', context)


def scroll_reader_view(request):
    context = get_feeds_context('scroll.in', 'Scroll.in')
    return render(request, 'feed_reader.html', context)


def the_news_minute_reader_view(request):
    context = get_feeds_context('www.thenewsminute.com', 'The News Minute')
    return render(request, 'feed_reader.html', context)
